spring:
   profiles:
     active: dev
---
spring:
   profiles: dev
   application:
     name: microservice-config-lyy-dev
---
spring:
  profiles: test
  application:
    name: microservice-config-lyy-test

#保存为utf-8
